export enum DAT_FLAGS_740_750 {
    GROUND          = 0x00,
    ON_BOTTOM       = 0x01,
    ON_TOP          = 0x02,
    CONTAINER       = 0x03,
    STACKABLE       = 0x04,
    MULTI_USE       = 0x05,
    FORCE_USE       = 0x06,
    WRITABLE        = 0x07,
    WRITABLE_ONCE   = 0x08,
    FLUID_CONTAINER = 0x09,
    FLUID           = 0x0A,
    UNPASSABLE      = 0x0B,
    UNMOVABLE       = 0x0C,
    BLOCK_MISSILE   = 0x0D,
    BLOCK_PATHFINDER= 0x0E,
    PICKUPABLE      = 0x0F,
    LIGHT_INFO      = 0x10,
    FLOOR_CHANGE    = 0x11,
    FULL_GROUND     = 0x12,
    HAS_ELEVATION   = 0x13,
    HAS_OFFSET      = 0x14,
    UNKNOWN         = 0x15,
    MINIMAP         = 0x16,
    ROTATABLE       = 0x17,
    LYING_OBJECT    = 0x18,
    HANGABLE        = 0x19,
    VERTICAL        = 0x1A,
    HORIZONTAL      = 0x1B,
    ALWAYS_ANIMATE  = 0x1C,
    LENS_HELP       = 0x1D,
    END_OF_FLAGS    = 0xFF
}

export enum DAT_FLAGS_755_772 {
    GROUND          = 0x00,
    GROUND_BORDER   = 0x01,
    ON_BOTTOM       = 0x02,
    ON_TOP          = 0x03,
    CONTAINER       = 0x04,
    STACKABLE       = 0x05,
    FORCE_USE       = 0x06,
    MULTI_USE       = 0x07,
    WRITABLE        = 0x08,
    WRITABLE_ONCE   = 0x09,
    FLUID_CONTAINER = 0x0A,
    FLUID           = 0x0B,
    UNPASSABLE      = 0x0C,
    UNMOVABLE       = 0x0D,
    BLOCK_MISSILE   = 0x0E,
    BLOCK_PATHFINDER= 0x0F,
    PICKUPABLE      = 0x10,
    HANGABLE        = 0x11,
    VERTICAL        = 0x12,
    HORIZONTAL      = 0x13,
    ROTATABLE       = 0x14,
    LIGHT_INFO      = 0x15,
    DONT_HIDE       = 0x16,
    FLOOR_CHANGE    = 0x17,
    HAS_OFFSET      = 0x18,
    HAS_ELEVATION   = 0x19,
    LYING_OBJECT    = 0x1A,
    ALWAYS_ANIMATE  = 0x1B,
    MINIMAP         = 0x1C,
    LENS_HELP       = 0x1D,
    FULL_GROUND     = 0x1E,
    END_OF_FLAGS    = 0xFF
}

export enum DAT_FLAG_NAMES {
    GROUND          = 'ground',
    GROUND_BORDER   = 'groundBorder',
    ON_BOTTOM       = 'onBottom',
    ON_TOP          = 'onTop',
    CONTAINER       = 'container',
    STACKABLE       = 'stackable',
    MULTI_USEABLE   = 'multiUseable',
    FORCE_USE       = 'forceUse',
    WRITABLE        = 'writable',
    WRITABLE_ONCE   = 'writableOnce',
    FLUID_CONTAINER = 'fluidContainer',
    FLUID           = 'fluid',
    UNPASSABLE      = 'unpassable',
    UNMOVABLE       = 'unmovable',
    BLOCK_MISSILE   = 'blockMissile',
    BLOCK_PATHFINDER= 'blockPathfinder',
    PICKUPABLE      = 'pickupable',
    LIGHT_INFO      = 'lightInfo',
    FLOOR_CHANGE    = 'floorChange',
    FULL_GROUND     = 'fullGround',
    HAS_ELEVATION   = 'hasElevation',
    HAS_OFFSET      = 'hasOffset',
    MINIMAP         = 'minimap',
    ROTATABLE       = 'rotatable',
    LYING_OBJECT    = 'lyingObject',
    HANGABLE        = 'hangable',
    VERTICAL        = 'vertical',
    HORIZONTAL      = 'horizontal',
    ALWAYS_ANIMATE  = 'alwaysAnimate',
    IS_LENS_HELP    = 'isLensHelp',
    DONT_HIDE       = 'dontHide'
}

export enum DAT_TEXTURE_NAMES {
    WIDTH           = 'width',
    HEIGHT          = 'height',
    LAYERS          = 'layers',
    PATTERN_X       = 'patternX',
    PATTERN_Y       = 'patternY',
    PATTERN_Z       = 'patternZ',
    ANIMATION       = 'animations',
    REAL_SIZE       = 'realSize',
    EXACT_SIZE      = 'exactSize'
}

export enum THING_CATEGORY {
    ITEM            = 'ITEM',
    LOOKTYPE        = 'LOOKTYPE',
    EFFECT          = 'EFFECT',
    MISSILE         = 'MISSILE',
    UNKNOWN         = 'UNKNOWN'
}

export const DAT_SIGNATURES = {
    710             : '3DFF4B2A',
    713             : '3FD4FB91',
    721             : '3FDF40C6',
    724             : '404E1C14',
    726             : '404E1C14',
    727             : '404E1C14',
    730             : '411A6233',
    740             : '41BF619C',
    741             : '41BF619C',
    750             : '42F81973',
    755             : '437B2B8F',
    760             : '439D5A33',
    770             : '439D5A33',
    772             : '439D5A33'
}